// flow-typed signature: ff844621b064edb7a60187aaf4c0c584
// flow-typed version: <<STUB>>/clsx_v^1.0.4/flow_v0.102.0-rc

/**
 * This is an autogenerated libdef stub for:
 *
 *   'clsx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'clsx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'clsx/dist/clsx' {
  declare module.exports: any;
}

declare module 'clsx/dist/clsx.m' {
  declare module.exports: any;
}

declare module 'clsx/dist/clsx.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'clsx/dist/clsx.js' {
  declare module.exports: $Exports<'clsx/dist/clsx'>;
}
declare module 'clsx/dist/clsx.m.js' {
  declare module.exports: $Exports<'clsx/dist/clsx.m'>;
}
declare module 'clsx/dist/clsx.min.js' {
  declare module.exports: $Exports<'clsx/dist/clsx.min'>;
}
