version: '3'
services:
  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    ports:
      - '${DB_PORT}:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${DB_ADMINUSERNAME}'
      MONGO_INITDB_ROOT_PASSWORD: '${DB_ADMINPASSWORD}'
