version: '3'
services:
 mongo:
    env_file:
      - .env
    image: mongo
    restart: always
    ports:
      - "${DB_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DB_ADMINUSERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_ADMINPASSWORD}"